In [ ]:
from ultralytics import YOLO
import cv2

model_path = 'last.pt'
image_path = 'MAH03602.MP4'

model=YOLO(model_path)
model.predict(source=image_path,
              show=True,
              conf=0.25,
              boxes=True,
              #retina_masks=True,
              vid_stride=True,
              classes=[0,2,3],
              visualize=True
              )

In [4]:
from ultralytics import YOLO
import cv2

model_path = 'last.pt'
image_path = 'testIMG.jpg'


model=YOLO(model_path)

results = model(image_path)  # results list

# View results
for r in results:
    mask=r.masks.numpy()  # print the Masks object containing the detected instance masks


image 1/1 c:\python\Setel_Project\testIMG.jpg: 320x448 2 Plants, 1 sky, 1 soil, 3 trunks, 43.9ms
Speed: 2.0ms preprocess, 43.9ms inference, 4.0ms postprocess per image at shape (1, 3, 320, 448)


In [8]:
print(mask.data)

[[[          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  ...
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]]

 [[          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  ...
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]]

 [[          0          